(()=>{
const BACKUP_KEY='ictL1State_full541_v3_backup';
const STATE_KEY='ictL1State_full541_v3';
const style=document.createElement('style');style.textContent=`.safety-tools{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.safety-tools button{border:1px solid #31577c;background:#0b2039;color:#d9edff;border-radius:12px;padding:10px 8px;font-weight:800}.safety-tools .restore{border-color:#426d55;background:#10291e;color:#a9efc2}.safety-tools .reset{border-color:#703a48;background:#321923;color:#ffadb8}@media(max-width:560px){.safety-tools{grid-template-columns:1fr 1fr}.safety-tools .reset{grid-column:1/-1}}`;document.head.appendChild(style);
const host=document.querySelector('.viewtabs')||document.getElementById('search');
const tools=document.createElement('div');tools.className='safety-tools';tools.innerHTML='<button id="backupState">💾 Backup</button><button id="restoreState" class="restore">🛟 Restore</button><button id="resetState" class="reset">♻️ Reset</button>';host.after(tools);
function snapshot(){try{save()}catch(e){}const raw=localStorage.getItem(STATE_KEY);if(raw)return raw;try{return JSON.stringify(state)}catch(e){return null}}
function makeBackup(){const raw=snapshot();if(!raw){alert('Backup කිරීමට data නැහැ.');return}localStorage.setItem(BACKUP_KEY,JSON.stringify({createdAt:new Date().toISOString(),data:raw}));alert('✅ Backup එක සුරක්ෂිතව save කළා. Reset කළත් මේ backup එක තියාගන්නවා.')}
function restoreBackup(){const packed=localStorage.getItem(BACKUP_KEY);if(!packed){alert('Backup එකක් තවම නැහැ.');return}if(!confirm('🛟 අවසන් backup එක restore කරන්නද?\n\nදැනට තියෙන app progress/data backup එකේ data වලින් replace වෙනවා.'))return;try{const b=JSON.parse(packed);if(!b||!b.data)throw Error('bad backup');localStorage.setItem(STATE_KEY,b.data);alert('✅ Backup restore කළා. App එක reload වෙනවා.');location.reload()}catch(e){alert('Backup එක restore කරන්න බැරි වුණා.') }}
function resetAll(){if(!confirm('⚠️ App data RESET කරන්නද?\n\nProgress, marks, saved questions, folders සහ notes reset වෙනවා. Backup එක මැකෙන්නේ නැහැ.'))return;if(!confirm('අවසන් තහවුරු කිරීම: ඇත්තටම RESET කරන්නද?'))return;const keep=localStorage.getItem(BACKUP_KEY);Object.keys(localStorage).filter(k=>k===STATE_KEY||k.startsWith('ictL1Timer_full541_v3_')).forEach(k=>localStorage.removeItem(k));if(keep)localStorage.setItem(BACKUP_KEY,keep);alert('♻️ Reset complete. Backup එක ආරක්ෂිතයි.');location.reload()}
document.getElementById('backupState').onclick=makeBackup;document.getElementById('restoreState').onclick=restoreBackup;document.getElementById('resetState').onclick=resetAll;
})();